package teenhealth.mybatis.mapper;

import teenhealth.mybatis.po.TblRole;
import teenhealth.mybatis.po.TblRoleExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface TblRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_role
     *
     * @mbggenerated Tue Mar 10 15:48:14 CST 2020
     */
    int countByExample(TblRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_role
     *
     * @mbggenerated Tue Mar 10 15:48:14 CST 2020
     */
    int deleteByExample(TblRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_role
     *
     * @mbggenerated Tue Mar 10 15:48:14 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_role
     *
     * @mbggenerated Tue Mar 10 15:48:14 CST 2020
     */
    int insert(TblRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_role
     *
     * @mbggenerated Tue Mar 10 15:48:14 CST 2020
     */
    int insertSelective(TblRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_role
     *
     * @mbggenerated Tue Mar 10 15:48:14 CST 2020
     */
    List<TblRole> selectByExample(TblRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_role
     *
     * @mbggenerated Tue Mar 10 15:48:14 CST 2020
     */
    TblRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_role
     *
     * @mbggenerated Tue Mar 10 15:48:14 CST 2020
     */
    int updateByExampleSelective(@Param("record") TblRole record, @Param("example") TblRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_role
     *
     * @mbggenerated Tue Mar 10 15:48:14 CST 2020
     */
    int updateByExample(@Param("record") TblRole record, @Param("example") TblRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_role
     *
     * @mbggenerated Tue Mar 10 15:48:14 CST 2020
     */
    int updateByPrimaryKeySelective(TblRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_role
     *
     * @mbggenerated Tue Mar 10 15:48:14 CST 2020
     */
    int updateByPrimaryKey(TblRole record);

    TblRole selectRoleName(String loginName);
}