package teenhealth.mybatis.mapper;

import teenhealth.mybatis.po.TEyesightPlan;
import teenhealth.mybatis.po.TEyesightPlanExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TEyesightPlanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_eyesight_plan
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    int countByExample(TEyesightPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_eyesight_plan
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    int deleteByExample(TEyesightPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_eyesight_plan
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_eyesight_plan
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    int insert(TEyesightPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_eyesight_plan
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    int insertSelective(TEyesightPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_eyesight_plan
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    List<TEyesightPlan> selectByExample(TEyesightPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_eyesight_plan
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    TEyesightPlan selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_eyesight_plan
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    int updateByExampleSelective(@Param("record") TEyesightPlan record, @Param("example") TEyesightPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_eyesight_plan
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    int updateByExample(@Param("record") TEyesightPlan record, @Param("example") TEyesightPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_eyesight_plan
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    int updateByPrimaryKeySelective(TEyesightPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_eyesight_plan
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    int updateByPrimaryKey(TEyesightPlan record);
}