package teenhealth.mybatis.mapper;

import teenhealth.mybatis.po.TEyesight;
import teenhealth.mybatis.po.TEyesightExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TEyesightMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_eyesight
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    int countByExample(TEyesightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_eyesight
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    int deleteByExample(TEyesightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_eyesight
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_eyesight
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    int insert(TEyesight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_eyesight
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    int insertSelective(TEyesight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_eyesight
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    List<TEyesight> selectByExample(TEyesightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_eyesight
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    TEyesight selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_eyesight
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    int updateByExampleSelective(@Param("record") TEyesight record, @Param("example") TEyesightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_eyesight
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    int updateByExample(@Param("record") TEyesight record, @Param("example") TEyesightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_eyesight
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    int updateByPrimaryKeySelective(TEyesight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_eyesight
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    int updateByPrimaryKey(TEyesight record);
}