package springboot.mybatis.po;

public class TblRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_role.id
     *
     * @mbggenerated Tue Mar 10 15:48:14 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_role.role_name
     *
     * @mbggenerated Tue Mar 10 15:48:14 CST 2020
     */
    private String roleName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_role.id
     *
     * @return the value of tbl_role.id
     *
     * @mbggenerated Tue Mar 10 15:48:14 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_role.id
     *
     * @param id the value for tbl_role.id
     *
     * @mbggenerated Tue Mar 10 15:48:14 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_role.role_name
     *
     * @return the value of tbl_role.role_name
     *
     * @mbggenerated Tue Mar 10 15:48:14 CST 2020
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_role.role_name
     *
     * @param roleName the value for tbl_role.role_name
     *
     * @mbggenerated Tue Mar 10 15:48:14 CST 2020
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }
}