package springboot.mybatis.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TCardiopulmonaryExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_cardiopulmonary
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_cardiopulmonary
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_cardiopulmonary
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cardiopulmonary
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public TCardiopulmonaryExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cardiopulmonary
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cardiopulmonary
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cardiopulmonary
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cardiopulmonary
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cardiopulmonary
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cardiopulmonary
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cardiopulmonary
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cardiopulmonary
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cardiopulmonary
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cardiopulmonary
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_cardiopulmonary
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andStudentIdIsNull() {
            addCriterion("student_id is null");
            return (Criteria) this;
        }

        public Criteria andStudentIdIsNotNull() {
            addCriterion("student_id is not null");
            return (Criteria) this;
        }

        public Criteria andStudentIdEqualTo(String value) {
            addCriterion("student_id =", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotEqualTo(String value) {
            addCriterion("student_id <>", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdGreaterThan(String value) {
            addCriterion("student_id >", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdGreaterThanOrEqualTo(String value) {
            addCriterion("student_id >=", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdLessThan(String value) {
            addCriterion("student_id <", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdLessThanOrEqualTo(String value) {
            addCriterion("student_id <=", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdLike(String value) {
            addCriterion("student_id like", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotLike(String value) {
            addCriterion("student_id not like", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdIn(List<String> values) {
            addCriterion("student_id in", values, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotIn(List<String> values) {
            addCriterion("student_id not in", values, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdBetween(String value1, String value2) {
            addCriterion("student_id between", value1, value2, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotBetween(String value1, String value2) {
            addCriterion("student_id not between", value1, value2, "studentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdIsNull() {
            addCriterion("equipment_id is null");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdIsNotNull() {
            addCriterion("equipment_id is not null");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdEqualTo(String value) {
            addCriterion("equipment_id =", value, "equipmentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdNotEqualTo(String value) {
            addCriterion("equipment_id <>", value, "equipmentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdGreaterThan(String value) {
            addCriterion("equipment_id >", value, "equipmentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdGreaterThanOrEqualTo(String value) {
            addCriterion("equipment_id >=", value, "equipmentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdLessThan(String value) {
            addCriterion("equipment_id <", value, "equipmentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdLessThanOrEqualTo(String value) {
            addCriterion("equipment_id <=", value, "equipmentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdLike(String value) {
            addCriterion("equipment_id like", value, "equipmentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdNotLike(String value) {
            addCriterion("equipment_id not like", value, "equipmentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdIn(List<String> values) {
            addCriterion("equipment_id in", values, "equipmentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdNotIn(List<String> values) {
            addCriterion("equipment_id not in", values, "equipmentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdBetween(String value1, String value2) {
            addCriterion("equipment_id between", value1, value2, "equipmentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdNotBetween(String value1, String value2) {
            addCriterion("equipment_id not between", value1, value2, "equipmentId");
            return (Criteria) this;
        }

        public Criteria andFirstSpeedIsNull() {
            addCriterion("first_speed is null");
            return (Criteria) this;
        }

        public Criteria andFirstSpeedIsNotNull() {
            addCriterion("first_speed is not null");
            return (Criteria) this;
        }

        public Criteria andFirstSpeedEqualTo(Integer value) {
            addCriterion("first_speed =", value, "firstSpeed");
            return (Criteria) this;
        }

        public Criteria andFirstSpeedNotEqualTo(Integer value) {
            addCriterion("first_speed <>", value, "firstSpeed");
            return (Criteria) this;
        }

        public Criteria andFirstSpeedGreaterThan(Integer value) {
            addCriterion("first_speed >", value, "firstSpeed");
            return (Criteria) this;
        }

        public Criteria andFirstSpeedGreaterThanOrEqualTo(Integer value) {
            addCriterion("first_speed >=", value, "firstSpeed");
            return (Criteria) this;
        }

        public Criteria andFirstSpeedLessThan(Integer value) {
            addCriterion("first_speed <", value, "firstSpeed");
            return (Criteria) this;
        }

        public Criteria andFirstSpeedLessThanOrEqualTo(Integer value) {
            addCriterion("first_speed <=", value, "firstSpeed");
            return (Criteria) this;
        }

        public Criteria andFirstSpeedIn(List<Integer> values) {
            addCriterion("first_speed in", values, "firstSpeed");
            return (Criteria) this;
        }

        public Criteria andFirstSpeedNotIn(List<Integer> values) {
            addCriterion("first_speed not in", values, "firstSpeed");
            return (Criteria) this;
        }

        public Criteria andFirstSpeedBetween(Integer value1, Integer value2) {
            addCriterion("first_speed between", value1, value2, "firstSpeed");
            return (Criteria) this;
        }

        public Criteria andFirstSpeedNotBetween(Integer value1, Integer value2) {
            addCriterion("first_speed not between", value1, value2, "firstSpeed");
            return (Criteria) this;
        }

        public Criteria andFirstHrIsNull() {
            addCriterion("first_hr is null");
            return (Criteria) this;
        }

        public Criteria andFirstHrIsNotNull() {
            addCriterion("first_hr is not null");
            return (Criteria) this;
        }

        public Criteria andFirstHrEqualTo(Integer value) {
            addCriterion("first_hr =", value, "firstHr");
            return (Criteria) this;
        }

        public Criteria andFirstHrNotEqualTo(Integer value) {
            addCriterion("first_hr <>", value, "firstHr");
            return (Criteria) this;
        }

        public Criteria andFirstHrGreaterThan(Integer value) {
            addCriterion("first_hr >", value, "firstHr");
            return (Criteria) this;
        }

        public Criteria andFirstHrGreaterThanOrEqualTo(Integer value) {
            addCriterion("first_hr >=", value, "firstHr");
            return (Criteria) this;
        }

        public Criteria andFirstHrLessThan(Integer value) {
            addCriterion("first_hr <", value, "firstHr");
            return (Criteria) this;
        }

        public Criteria andFirstHrLessThanOrEqualTo(Integer value) {
            addCriterion("first_hr <=", value, "firstHr");
            return (Criteria) this;
        }

        public Criteria andFirstHrIn(List<Integer> values) {
            addCriterion("first_hr in", values, "firstHr");
            return (Criteria) this;
        }

        public Criteria andFirstHrNotIn(List<Integer> values) {
            addCriterion("first_hr not in", values, "firstHr");
            return (Criteria) this;
        }

        public Criteria andFirstHrBetween(Integer value1, Integer value2) {
            addCriterion("first_hr between", value1, value2, "firstHr");
            return (Criteria) this;
        }

        public Criteria andFirstHrNotBetween(Integer value1, Integer value2) {
            addCriterion("first_hr not between", value1, value2, "firstHr");
            return (Criteria) this;
        }

        public Criteria andFirstPowerIsNull() {
            addCriterion("first_power is null");
            return (Criteria) this;
        }

        public Criteria andFirstPowerIsNotNull() {
            addCriterion("first_power is not null");
            return (Criteria) this;
        }

        public Criteria andFirstPowerEqualTo(Integer value) {
            addCriterion("first_power =", value, "firstPower");
            return (Criteria) this;
        }

        public Criteria andFirstPowerNotEqualTo(Integer value) {
            addCriterion("first_power <>", value, "firstPower");
            return (Criteria) this;
        }

        public Criteria andFirstPowerGreaterThan(Integer value) {
            addCriterion("first_power >", value, "firstPower");
            return (Criteria) this;
        }

        public Criteria andFirstPowerGreaterThanOrEqualTo(Integer value) {
            addCriterion("first_power >=", value, "firstPower");
            return (Criteria) this;
        }

        public Criteria andFirstPowerLessThan(Integer value) {
            addCriterion("first_power <", value, "firstPower");
            return (Criteria) this;
        }

        public Criteria andFirstPowerLessThanOrEqualTo(Integer value) {
            addCriterion("first_power <=", value, "firstPower");
            return (Criteria) this;
        }

        public Criteria andFirstPowerIn(List<Integer> values) {
            addCriterion("first_power in", values, "firstPower");
            return (Criteria) this;
        }

        public Criteria andFirstPowerNotIn(List<Integer> values) {
            addCriterion("first_power not in", values, "firstPower");
            return (Criteria) this;
        }

        public Criteria andFirstPowerBetween(Integer value1, Integer value2) {
            addCriterion("first_power between", value1, value2, "firstPower");
            return (Criteria) this;
        }

        public Criteria andFirstPowerNotBetween(Integer value1, Integer value2) {
            addCriterion("first_power not between", value1, value2, "firstPower");
            return (Criteria) this;
        }

        public Criteria andSecondSpeedIsNull() {
            addCriterion("second_speed is null");
            return (Criteria) this;
        }

        public Criteria andSecondSpeedIsNotNull() {
            addCriterion("second_speed is not null");
            return (Criteria) this;
        }

        public Criteria andSecondSpeedEqualTo(Integer value) {
            addCriterion("second_speed =", value, "secondSpeed");
            return (Criteria) this;
        }

        public Criteria andSecondSpeedNotEqualTo(Integer value) {
            addCriterion("second_speed <>", value, "secondSpeed");
            return (Criteria) this;
        }

        public Criteria andSecondSpeedGreaterThan(Integer value) {
            addCriterion("second_speed >", value, "secondSpeed");
            return (Criteria) this;
        }

        public Criteria andSecondSpeedGreaterThanOrEqualTo(Integer value) {
            addCriterion("second_speed >=", value, "secondSpeed");
            return (Criteria) this;
        }

        public Criteria andSecondSpeedLessThan(Integer value) {
            addCriterion("second_speed <", value, "secondSpeed");
            return (Criteria) this;
        }

        public Criteria andSecondSpeedLessThanOrEqualTo(Integer value) {
            addCriterion("second_speed <=", value, "secondSpeed");
            return (Criteria) this;
        }

        public Criteria andSecondSpeedIn(List<Integer> values) {
            addCriterion("second_speed in", values, "secondSpeed");
            return (Criteria) this;
        }

        public Criteria andSecondSpeedNotIn(List<Integer> values) {
            addCriterion("second_speed not in", values, "secondSpeed");
            return (Criteria) this;
        }

        public Criteria andSecondSpeedBetween(Integer value1, Integer value2) {
            addCriterion("second_speed between", value1, value2, "secondSpeed");
            return (Criteria) this;
        }

        public Criteria andSecondSpeedNotBetween(Integer value1, Integer value2) {
            addCriterion("second_speed not between", value1, value2, "secondSpeed");
            return (Criteria) this;
        }

        public Criteria andSecondHrIsNull() {
            addCriterion("second_hr is null");
            return (Criteria) this;
        }

        public Criteria andSecondHrIsNotNull() {
            addCriterion("second_hr is not null");
            return (Criteria) this;
        }

        public Criteria andSecondHrEqualTo(Integer value) {
            addCriterion("second_hr =", value, "secondHr");
            return (Criteria) this;
        }

        public Criteria andSecondHrNotEqualTo(Integer value) {
            addCriterion("second_hr <>", value, "secondHr");
            return (Criteria) this;
        }

        public Criteria andSecondHrGreaterThan(Integer value) {
            addCriterion("second_hr >", value, "secondHr");
            return (Criteria) this;
        }

        public Criteria andSecondHrGreaterThanOrEqualTo(Integer value) {
            addCriterion("second_hr >=", value, "secondHr");
            return (Criteria) this;
        }

        public Criteria andSecondHrLessThan(Integer value) {
            addCriterion("second_hr <", value, "secondHr");
            return (Criteria) this;
        }

        public Criteria andSecondHrLessThanOrEqualTo(Integer value) {
            addCriterion("second_hr <=", value, "secondHr");
            return (Criteria) this;
        }

        public Criteria andSecondHrIn(List<Integer> values) {
            addCriterion("second_hr in", values, "secondHr");
            return (Criteria) this;
        }

        public Criteria andSecondHrNotIn(List<Integer> values) {
            addCriterion("second_hr not in", values, "secondHr");
            return (Criteria) this;
        }

        public Criteria andSecondHrBetween(Integer value1, Integer value2) {
            addCriterion("second_hr between", value1, value2, "secondHr");
            return (Criteria) this;
        }

        public Criteria andSecondHrNotBetween(Integer value1, Integer value2) {
            addCriterion("second_hr not between", value1, value2, "secondHr");
            return (Criteria) this;
        }

        public Criteria andSecondPowerIsNull() {
            addCriterion("second_power is null");
            return (Criteria) this;
        }

        public Criteria andSecondPowerIsNotNull() {
            addCriterion("second_power is not null");
            return (Criteria) this;
        }

        public Criteria andSecondPowerEqualTo(Integer value) {
            addCriterion("second_power =", value, "secondPower");
            return (Criteria) this;
        }

        public Criteria andSecondPowerNotEqualTo(Integer value) {
            addCriterion("second_power <>", value, "secondPower");
            return (Criteria) this;
        }

        public Criteria andSecondPowerGreaterThan(Integer value) {
            addCriterion("second_power >", value, "secondPower");
            return (Criteria) this;
        }

        public Criteria andSecondPowerGreaterThanOrEqualTo(Integer value) {
            addCriterion("second_power >=", value, "secondPower");
            return (Criteria) this;
        }

        public Criteria andSecondPowerLessThan(Integer value) {
            addCriterion("second_power <", value, "secondPower");
            return (Criteria) this;
        }

        public Criteria andSecondPowerLessThanOrEqualTo(Integer value) {
            addCriterion("second_power <=", value, "secondPower");
            return (Criteria) this;
        }

        public Criteria andSecondPowerIn(List<Integer> values) {
            addCriterion("second_power in", values, "secondPower");
            return (Criteria) this;
        }

        public Criteria andSecondPowerNotIn(List<Integer> values) {
            addCriterion("second_power not in", values, "secondPower");
            return (Criteria) this;
        }

        public Criteria andSecondPowerBetween(Integer value1, Integer value2) {
            addCriterion("second_power between", value1, value2, "secondPower");
            return (Criteria) this;
        }

        public Criteria andSecondPowerNotBetween(Integer value1, Integer value2) {
            addCriterion("second_power not between", value1, value2, "secondPower");
            return (Criteria) this;
        }

        public Criteria andMaxPowerIsNull() {
            addCriterion("max_power is null");
            return (Criteria) this;
        }

        public Criteria andMaxPowerIsNotNull() {
            addCriterion("max_power is not null");
            return (Criteria) this;
        }

        public Criteria andMaxPowerEqualTo(Integer value) {
            addCriterion("max_power =", value, "maxPower");
            return (Criteria) this;
        }

        public Criteria andMaxPowerNotEqualTo(Integer value) {
            addCriterion("max_power <>", value, "maxPower");
            return (Criteria) this;
        }

        public Criteria andMaxPowerGreaterThan(Integer value) {
            addCriterion("max_power >", value, "maxPower");
            return (Criteria) this;
        }

        public Criteria andMaxPowerGreaterThanOrEqualTo(Integer value) {
            addCriterion("max_power >=", value, "maxPower");
            return (Criteria) this;
        }

        public Criteria andMaxPowerLessThan(Integer value) {
            addCriterion("max_power <", value, "maxPower");
            return (Criteria) this;
        }

        public Criteria andMaxPowerLessThanOrEqualTo(Integer value) {
            addCriterion("max_power <=", value, "maxPower");
            return (Criteria) this;
        }

        public Criteria andMaxPowerIn(List<Integer> values) {
            addCriterion("max_power in", values, "maxPower");
            return (Criteria) this;
        }

        public Criteria andMaxPowerNotIn(List<Integer> values) {
            addCriterion("max_power not in", values, "maxPower");
            return (Criteria) this;
        }

        public Criteria andMaxPowerBetween(Integer value1, Integer value2) {
            addCriterion("max_power between", value1, value2, "maxPower");
            return (Criteria) this;
        }

        public Criteria andMaxPowerNotBetween(Integer value1, Integer value2) {
            addCriterion("max_power not between", value1, value2, "maxPower");
            return (Criteria) this;
        }

        public Criteria andScoreIsNull() {
            addCriterion("score is null");
            return (Criteria) this;
        }

        public Criteria andScoreIsNotNull() {
            addCriterion("score is not null");
            return (Criteria) this;
        }

        public Criteria andScoreEqualTo(Integer value) {
            addCriterion("score =", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotEqualTo(Integer value) {
            addCriterion("score <>", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreGreaterThan(Integer value) {
            addCriterion("score >", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("score >=", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreLessThan(Integer value) {
            addCriterion("score <", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreLessThanOrEqualTo(Integer value) {
            addCriterion("score <=", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreIn(List<Integer> values) {
            addCriterion("score in", values, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotIn(List<Integer> values) {
            addCriterion("score not in", values, "score");
            return (Criteria) this;
        }

        public Criteria andScoreBetween(Integer value1, Integer value2) {
            addCriterion("score between", value1, value2, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotBetween(Integer value1, Integer value2) {
            addCriterion("score not between", value1, value2, "score");
            return (Criteria) this;
        }

        public Criteria andHeartRateIsNull() {
            addCriterion("heart_rate is null");
            return (Criteria) this;
        }

        public Criteria andHeartRateIsNotNull() {
            addCriterion("heart_rate is not null");
            return (Criteria) this;
        }

        public Criteria andHeartRateEqualTo(Integer value) {
            addCriterion("heart_rate =", value, "heartRate");
            return (Criteria) this;
        }

        public Criteria andHeartRateNotEqualTo(Integer value) {
            addCriterion("heart_rate <>", value, "heartRate");
            return (Criteria) this;
        }

        public Criteria andHeartRateGreaterThan(Integer value) {
            addCriterion("heart_rate >", value, "heartRate");
            return (Criteria) this;
        }

        public Criteria andHeartRateGreaterThanOrEqualTo(Integer value) {
            addCriterion("heart_rate >=", value, "heartRate");
            return (Criteria) this;
        }

        public Criteria andHeartRateLessThan(Integer value) {
            addCriterion("heart_rate <", value, "heartRate");
            return (Criteria) this;
        }

        public Criteria andHeartRateLessThanOrEqualTo(Integer value) {
            addCriterion("heart_rate <=", value, "heartRate");
            return (Criteria) this;
        }

        public Criteria andHeartRateIn(List<Integer> values) {
            addCriterion("heart_rate in", values, "heartRate");
            return (Criteria) this;
        }

        public Criteria andHeartRateNotIn(List<Integer> values) {
            addCriterion("heart_rate not in", values, "heartRate");
            return (Criteria) this;
        }

        public Criteria andHeartRateBetween(Integer value1, Integer value2) {
            addCriterion("heart_rate between", value1, value2, "heartRate");
            return (Criteria) this;
        }

        public Criteria andHeartRateNotBetween(Integer value1, Integer value2) {
            addCriterion("heart_rate not between", value1, value2, "heartRate");
            return (Criteria) this;
        }

        public Criteria andOxygenUptakeIsNull() {
            addCriterion("oxygen_uptake is null");
            return (Criteria) this;
        }

        public Criteria andOxygenUptakeIsNotNull() {
            addCriterion("oxygen_uptake is not null");
            return (Criteria) this;
        }

        public Criteria andOxygenUptakeEqualTo(Double value) {
            addCriterion("oxygen_uptake =", value, "oxygenUptake");
            return (Criteria) this;
        }

        public Criteria andOxygenUptakeNotEqualTo(Double value) {
            addCriterion("oxygen_uptake <>", value, "oxygenUptake");
            return (Criteria) this;
        }

        public Criteria andOxygenUptakeGreaterThan(Double value) {
            addCriterion("oxygen_uptake >", value, "oxygenUptake");
            return (Criteria) this;
        }

        public Criteria andOxygenUptakeGreaterThanOrEqualTo(Double value) {
            addCriterion("oxygen_uptake >=", value, "oxygenUptake");
            return (Criteria) this;
        }

        public Criteria andOxygenUptakeLessThan(Double value) {
            addCriterion("oxygen_uptake <", value, "oxygenUptake");
            return (Criteria) this;
        }

        public Criteria andOxygenUptakeLessThanOrEqualTo(Double value) {
            addCriterion("oxygen_uptake <=", value, "oxygenUptake");
            return (Criteria) this;
        }

        public Criteria andOxygenUptakeIn(List<Double> values) {
            addCriterion("oxygen_uptake in", values, "oxygenUptake");
            return (Criteria) this;
        }

        public Criteria andOxygenUptakeNotIn(List<Double> values) {
            addCriterion("oxygen_uptake not in", values, "oxygenUptake");
            return (Criteria) this;
        }

        public Criteria andOxygenUptakeBetween(Double value1, Double value2) {
            addCriterion("oxygen_uptake between", value1, value2, "oxygenUptake");
            return (Criteria) this;
        }

        public Criteria andOxygenUptakeNotBetween(Double value1, Double value2) {
            addCriterion("oxygen_uptake not between", value1, value2, "oxygenUptake");
            return (Criteria) this;
        }

        public Criteria andIntHrKIsNull() {
            addCriterion("int_hr_k is null");
            return (Criteria) this;
        }

        public Criteria andIntHrKIsNotNull() {
            addCriterion("int_hr_k is not null");
            return (Criteria) this;
        }

        public Criteria andIntHrKEqualTo(Double value) {
            addCriterion("int_hr_k =", value, "intHrK");
            return (Criteria) this;
        }

        public Criteria andIntHrKNotEqualTo(Double value) {
            addCriterion("int_hr_k <>", value, "intHrK");
            return (Criteria) this;
        }

        public Criteria andIntHrKGreaterThan(Double value) {
            addCriterion("int_hr_k >", value, "intHrK");
            return (Criteria) this;
        }

        public Criteria andIntHrKGreaterThanOrEqualTo(Double value) {
            addCriterion("int_hr_k >=", value, "intHrK");
            return (Criteria) this;
        }

        public Criteria andIntHrKLessThan(Double value) {
            addCriterion("int_hr_k <", value, "intHrK");
            return (Criteria) this;
        }

        public Criteria andIntHrKLessThanOrEqualTo(Double value) {
            addCriterion("int_hr_k <=", value, "intHrK");
            return (Criteria) this;
        }

        public Criteria andIntHrKIn(List<Double> values) {
            addCriterion("int_hr_k in", values, "intHrK");
            return (Criteria) this;
        }

        public Criteria andIntHrKNotIn(List<Double> values) {
            addCriterion("int_hr_k not in", values, "intHrK");
            return (Criteria) this;
        }

        public Criteria andIntHrKBetween(Double value1, Double value2) {
            addCriterion("int_hr_k between", value1, value2, "intHrK");
            return (Criteria) this;
        }

        public Criteria andIntHrKNotBetween(Double value1, Double value2) {
            addCriterion("int_hr_k not between", value1, value2, "intHrK");
            return (Criteria) this;
        }

        public Criteria andIntHrBIsNull() {
            addCriterion("int_hr_b is null");
            return (Criteria) this;
        }

        public Criteria andIntHrBIsNotNull() {
            addCriterion("int_hr_b is not null");
            return (Criteria) this;
        }

        public Criteria andIntHrBEqualTo(Double value) {
            addCriterion("int_hr_b =", value, "intHrB");
            return (Criteria) this;
        }

        public Criteria andIntHrBNotEqualTo(Double value) {
            addCriterion("int_hr_b <>", value, "intHrB");
            return (Criteria) this;
        }

        public Criteria andIntHrBGreaterThan(Double value) {
            addCriterion("int_hr_b >", value, "intHrB");
            return (Criteria) this;
        }

        public Criteria andIntHrBGreaterThanOrEqualTo(Double value) {
            addCriterion("int_hr_b >=", value, "intHrB");
            return (Criteria) this;
        }

        public Criteria andIntHrBLessThan(Double value) {
            addCriterion("int_hr_b <", value, "intHrB");
            return (Criteria) this;
        }

        public Criteria andIntHrBLessThanOrEqualTo(Double value) {
            addCriterion("int_hr_b <=", value, "intHrB");
            return (Criteria) this;
        }

        public Criteria andIntHrBIn(List<Double> values) {
            addCriterion("int_hr_b in", values, "intHrB");
            return (Criteria) this;
        }

        public Criteria andIntHrBNotIn(List<Double> values) {
            addCriterion("int_hr_b not in", values, "intHrB");
            return (Criteria) this;
        }

        public Criteria andIntHrBBetween(Double value1, Double value2) {
            addCriterion("int_hr_b between", value1, value2, "intHrB");
            return (Criteria) this;
        }

        public Criteria andIntHrBNotBetween(Double value1, Double value2) {
            addCriterion("int_hr_b not between", value1, value2, "intHrB");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUploadTimeIsNull() {
            addCriterion("upload_time is null");
            return (Criteria) this;
        }

        public Criteria andUploadTimeIsNotNull() {
            addCriterion("upload_time is not null");
            return (Criteria) this;
        }

        public Criteria andUploadTimeEqualTo(Date value) {
            addCriterion("upload_time =", value, "uploadTime");
            return (Criteria) this;
        }

        public Criteria andUploadTimeNotEqualTo(Date value) {
            addCriterion("upload_time <>", value, "uploadTime");
            return (Criteria) this;
        }

        public Criteria andUploadTimeGreaterThan(Date value) {
            addCriterion("upload_time >", value, "uploadTime");
            return (Criteria) this;
        }

        public Criteria andUploadTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("upload_time >=", value, "uploadTime");
            return (Criteria) this;
        }

        public Criteria andUploadTimeLessThan(Date value) {
            addCriterion("upload_time <", value, "uploadTime");
            return (Criteria) this;
        }

        public Criteria andUploadTimeLessThanOrEqualTo(Date value) {
            addCriterion("upload_time <=", value, "uploadTime");
            return (Criteria) this;
        }

        public Criteria andUploadTimeIn(List<Date> values) {
            addCriterion("upload_time in", values, "uploadTime");
            return (Criteria) this;
        }

        public Criteria andUploadTimeNotIn(List<Date> values) {
            addCriterion("upload_time not in", values, "uploadTime");
            return (Criteria) this;
        }

        public Criteria andUploadTimeBetween(Date value1, Date value2) {
            addCriterion("upload_time between", value1, value2, "uploadTime");
            return (Criteria) this;
        }

        public Criteria andUploadTimeNotBetween(Date value1, Date value2) {
            addCriterion("upload_time not between", value1, value2, "uploadTime");
            return (Criteria) this;
        }

        public Criteria andFcIsNull() {
            addCriterion("fc is null");
            return (Criteria) this;
        }

        public Criteria andFcIsNotNull() {
            addCriterion("fc is not null");
            return (Criteria) this;
        }

        public Criteria andFcEqualTo(Double value) {
            addCriterion("fc =", value, "fc");
            return (Criteria) this;
        }

        public Criteria andFcNotEqualTo(Double value) {
            addCriterion("fc <>", value, "fc");
            return (Criteria) this;
        }

        public Criteria andFcGreaterThan(Double value) {
            addCriterion("fc >", value, "fc");
            return (Criteria) this;
        }

        public Criteria andFcGreaterThanOrEqualTo(Double value) {
            addCriterion("fc >=", value, "fc");
            return (Criteria) this;
        }

        public Criteria andFcLessThan(Double value) {
            addCriterion("fc <", value, "fc");
            return (Criteria) this;
        }

        public Criteria andFcLessThanOrEqualTo(Double value) {
            addCriterion("fc <=", value, "fc");
            return (Criteria) this;
        }

        public Criteria andFcIn(List<Double> values) {
            addCriterion("fc in", values, "fc");
            return (Criteria) this;
        }

        public Criteria andFcNotIn(List<Double> values) {
            addCriterion("fc not in", values, "fc");
            return (Criteria) this;
        }

        public Criteria andFcBetween(Double value1, Double value2) {
            addCriterion("fc between", value1, value2, "fc");
            return (Criteria) this;
        }

        public Criteria andFcNotBetween(Double value1, Double value2) {
            addCriterion("fc not between", value1, value2, "fc");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_cardiopulmonary
     *
     * @mbggenerated do_not_delete_during_merge Sat Mar 07 21:35:32 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_cardiopulmonary
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}