package springboot.mybatis.po;

import java.util.Date;

public class TEquipment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_equipment.school_id
     *
     * @mbggenerated Wed May 06 22:49:17 CST 2020
     */
    private String id;

    private String equipmentNo;

    public String getId() {
        return id;
    }

    private String schoolId;

    private String typeId;

    private Integer status;

    private String createId;

    private Date createTime;

    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    public String getEquipmentNo() {
        return equipmentNo;
    }

    public void setEquipmentNo(String equipmentNo) {
        this.equipmentNo = equipmentNo == null ? null : equipmentNo.trim();
    }

    public String getSchoolId() {
        return schoolId;
    }

    public void setSchoolId(String schoolId) {
        this.schoolId = schoolId == null ? null : schoolId.trim();
    }

    public String getTypeId() {
        return typeId;
    }

    public void setTypeId(String typeId) {
        this.typeId = typeId == null ? null : typeId.trim();
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getCreateId() {
        return createId;
    }

    public void setCreateId(String createId) {
        this.createId = createId == null ? null : createId.trim();
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}