package springboot.mybatis.po;

import java.util.Date;

public class TEyesightPlan {

    private String id;

    private String studentId;

    private Integer exemode;

    private Integer exelength;

    private Integer exefreq;

    private Integer isEnable;

    private Date createTime;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_eyesight_plan.student_id
     *
     * @return the value of t_eyesight_plan.student_id
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public String getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_eyesight_plan.student_id
     *
     * @param studentId the value for t_eyesight_plan.student_id
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public void setStudentId(String studentId) {
        this.studentId = studentId == null ? null : studentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_eyesight_plan.exemode
     *
     * @return the value of t_eyesight_plan.exemode
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public Integer getExemode() {
        return exemode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_eyesight_plan.exemode
     *
     * @param exemode the value for t_eyesight_plan.exemode
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public void setExemode(Integer exemode) {
        this.exemode = exemode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_eyesight_plan.exelength
     *
     * @return the value of t_eyesight_plan.exelength
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public Integer getExelength() {
        return exelength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_eyesight_plan.exelength
     *
     * @param exelength the value for t_eyesight_plan.exelength
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public void setExelength(Integer exelength) {
        this.exelength = exelength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_eyesight_plan.exefreq
     *
     * @return the value of t_eyesight_plan.exefreq
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public Integer getExefreq() {
        return exefreq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_eyesight_plan.exefreq
     *
     * @param exefreq the value for t_eyesight_plan.exefreq
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public void setExefreq(Integer exefreq) {
        this.exefreq = exefreq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_eyesight_plan.is_enable
     *
     * @return the value of t_eyesight_plan.is_enable
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public Integer getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_eyesight_plan.is_enable
     *
     * @param isEnable the value for t_eyesight_plan.is_enable
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public void setIsEnable(Integer isEnable) {
        this.isEnable = isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_eyesight_plan.create_time
     *
     * @return the value of t_eyesight_plan.create_time
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_eyesight_plan.create_time
     *
     * @param createTime the value for t_eyesight_plan.create_time
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}