package springboot.mybatis.po;

public class TSomaticGameWithBLOBs extends TSomaticGame {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_somatic_game.sugg_flex
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    private String suggFlex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_somatic_game.sugg_blan
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    private String suggBlan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_somatic_game.sugg_jump
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    private String suggJump;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_somatic_game.sugg_choosetime
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    private String suggChoosetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_somatic_game.sugg_flex
     *
     * @return the value of t_somatic_game.sugg_flex
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public String getSuggFlex() {
        return suggFlex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_somatic_game.sugg_flex
     *
     * @param suggFlex the value for t_somatic_game.sugg_flex
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public void setSuggFlex(String suggFlex) {
        this.suggFlex = suggFlex == null ? null : suggFlex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_somatic_game.sugg_blan
     *
     * @return the value of t_somatic_game.sugg_blan
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public String getSuggBlan() {
        return suggBlan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_somatic_game.sugg_blan
     *
     * @param suggBlan the value for t_somatic_game.sugg_blan
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public void setSuggBlan(String suggBlan) {
        this.suggBlan = suggBlan == null ? null : suggBlan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_somatic_game.sugg_jump
     *
     * @return the value of t_somatic_game.sugg_jump
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public String getSuggJump() {
        return suggJump;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_somatic_game.sugg_jump
     *
     * @param suggJump the value for t_somatic_game.sugg_jump
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public void setSuggJump(String suggJump) {
        this.suggJump = suggJump == null ? null : suggJump.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_somatic_game.sugg_choosetime
     *
     * @return the value of t_somatic_game.sugg_choosetime
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public String getSuggChoosetime() {
        return suggChoosetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_somatic_game.sugg_choosetime
     *
     * @param suggChoosetime the value for t_somatic_game.sugg_choosetime
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public void setSuggChoosetime(String suggChoosetime) {
        this.suggChoosetime = suggChoosetime == null ? null : suggChoosetime.trim();
    }
}