package springboot.mybatis.po;

import java.util.Date;

public class TStudent {
    private String id;

    private String studentNo;

    private String studentName;

    private String classId;

    private String schoolId;

    private Integer age;

    private Integer sex;

    private Double stature;

    private Double weight;

    private Integer heartRate;

    private String idCard;

    private Date createTime;

    private String medical;

    private Integer phoneNo;

    private Double leftSight;

    private Double rightSight;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.student_no
     *
     * @return the value of t_student.student_no
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public String getStudentNo() {
        return studentNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.student_no
     *
     * @param studentNo the value for t_student.student_no
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public void setStudentNo(String studentNo) {
        this.studentNo = studentNo == null ? null : studentNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.student_name
     *
     * @return the value of t_student.student_name
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.student_name
     *
     * @param studentName the value for t_student.student_name
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName == null ? null : studentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.class_id
     *
     * @return the value of t_student.class_id
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public String getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.class_id
     *
     * @param classId the value for t_student.class_id
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public void setClassId(String classId) {
        this.classId = classId == null ? null : classId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.school_id
     *
     * @return the value of t_student.school_id
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public String getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.school_id
     *
     * @param schoolId the value for t_student.school_id
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public void setSchoolId(String schoolId) {
        this.schoolId = schoolId == null ? null : schoolId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.age
     *
     * @return the value of t_student.age
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.age
     *
     * @param age the value for t_student.age
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.sex
     *
     * @return the value of t_student.sex
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.sex
     *
     * @param sex the value for t_student.sex
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.stature
     *
     * @return the value of t_student.stature
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public Double getStature() {
        return stature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.stature
     *
     * @param stature the value for t_student.stature
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public void setStature(Double stature) {
        this.stature = stature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.weight
     *
     * @return the value of t_student.weight
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public Double getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.weight
     *
     * @param weight the value for t_student.weight
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public void setWeight(Double weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.heart_rate
     *
     * @return the value of t_student.heart_rate
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public Integer getHeartRate() {
        return heartRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.heart_rate
     *
     * @param heartRate the value for t_student.heart_rate
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public void setHeartRate(Integer heartRate) {
        this.heartRate = heartRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.id_card
     *
     * @return the value of t_student.id_card
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.id_card
     *
     * @param idCard the value for t_student.id_card
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.create_time
     *
     * @return the value of t_student.create_time
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.create_time
     *
     * @param createTime the value for t_student.create_time
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.medical
     *
     * @return the value of t_student.medical
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public String getMedical() {
        return medical;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.medical
     *
     * @param medical the value for t_student.medical
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public void setMedical(String medical) {
        this.medical = medical == null ? null : medical.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.phone_no
     *
     * @return the value of t_student.phone_no
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public Integer getPhoneNo() {
        return phoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.phone_no
     *
     * @param phoneNo the value for t_student.phone_no
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public void setPhoneNo(Integer phoneNo) {
        this.phoneNo = phoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.left_sight
     *
     * @return the value of t_student.left_sight
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public Double getLeftSight() {
        return leftSight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.left_sight
     *
     * @param leftSight the value for t_student.left_sight
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public void setLeftSight(Double leftSight) {
        this.leftSight = leftSight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.right_sight
     *
     * @return the value of t_student.right_sight
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public Double getRightSight() {
        return rightSight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.right_sight
     *
     * @param rightSight the value for t_student.right_sight
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public void setRightSight(Double rightSight) {
        this.rightSight = rightSight;
    }
}