package springboot.mybatis.po;

public class TTeacher {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.id
     *
     * @mbggenerated Wed Apr 15 11:42:33 CST 2020
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.teacher_name
     *
     * @mbggenerated Wed Apr 15 11:42:33 CST 2020
     */
    private String teacherName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.school_id
     *
     * @mbggenerated Wed Apr 15 11:42:33 CST 2020
     */
    private String schoolId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.user_id
     *
     * @mbggenerated Wed Apr 15 11:42:33 CST 2020
     */
    private String userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.id
     *
     * @return the value of t_teacher.id
     *
     * @mbggenerated Wed Apr 15 11:42:33 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.id
     *
     * @param id the value for t_teacher.id
     *
     * @mbggenerated Wed Apr 15 11:42:33 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.teacher_name
     *
     * @return the value of t_teacher.teacher_name
     *
     * @mbggenerated Wed Apr 15 11:42:33 CST 2020
     */
    public String getTeacherName() {
        return teacherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.teacher_name
     *
     * @param teacherName the value for t_teacher.teacher_name
     *
     * @mbggenerated Wed Apr 15 11:42:33 CST 2020
     */
    public void setTeacherName(String teacherName) {
        this.teacherName = teacherName == null ? null : teacherName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.school_id
     *
     * @return the value of t_teacher.school_id
     *
     * @mbggenerated Wed Apr 15 11:42:33 CST 2020
     */
    public String getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.school_id
     *
     * @param schoolId the value for t_teacher.school_id
     *
     * @mbggenerated Wed Apr 15 11:42:33 CST 2020
     */
    public void setSchoolId(String schoolId) {
        this.schoolId = schoolId == null ? null : schoolId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.user_id
     *
     * @return the value of t_teacher.user_id
     *
     * @mbggenerated Wed Apr 15 11:42:33 CST 2020
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.user_id
     *
     * @param userId the value for t_teacher.user_id
     *
     * @mbggenerated Wed Apr 15 11:42:33 CST 2020
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }
}