package springboot.mybatis.mapper;

import springboot.mybatis.po.TblUserRole;
import springboot.mybatis.po.TblUserRoleExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface TblUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user_role
     *
     * @mbggenerated Tue Mar 10 15:48:14 CST 2020
     */
    int countByExample(TblUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user_role
     *
     * @mbggenerated Tue Mar 10 15:48:14 CST 2020
     */
    int deleteByExample(TblUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user_role
     *
     * @mbggenerated Tue Mar 10 15:48:14 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user_role
     *
     * @mbggenerated Tue Mar 10 15:48:14 CST 2020
     */
    int insert(TblUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user_role
     *
     * @mbggenerated Tue Mar 10 15:48:14 CST 2020
     */
    int insertSelective(TblUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user_role
     *
     * @mbggenerated Tue Mar 10 15:48:14 CST 2020
     */
    List<TblUserRole> selectByExample(TblUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user_role
     *
     * @mbggenerated Tue Mar 10 15:48:14 CST 2020
     */
    TblUserRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user_role
     *
     * @mbggenerated Tue Mar 10 15:48:14 CST 2020
     */
    int updateByExampleSelective(@Param("record") TblUserRole record, @Param("example") TblUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user_role
     *
     * @mbggenerated Tue Mar 10 15:48:14 CST 2020
     */
    int updateByExample(@Param("record") TblUserRole record, @Param("example") TblUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user_role
     *
     * @mbggenerated Tue Mar 10 15:48:14 CST 2020
     */
    int updateByPrimaryKeySelective(TblUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user_role
     *
     * @mbggenerated Tue Mar 10 15:48:14 CST 2020
     */
    int updateByPrimaryKey(TblUserRole record);
}