package springboot.mybatis.mapper;

import springboot.mybatis.po.TEquipment;
import springboot.mybatis.po.TEquipmentExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TEquipmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_equipment
     *
     * @mbggenerated Wed May 06 22:49:17 CST 2020
     */
    int countByExample(TEquipmentExample example);

    int deleteByExample(TEquipmentExample example);

    int deleteByPrimaryKey(TEquipment key);

    int insert(TEquipment record);

    int insertSelective(TEquipment record);

    List<TEquipment> selectByExample(TEquipmentExample example);

    TEquipment selectByPrimaryKey(TEquipment key);

    int updateByExampleSelective(@Param("record") TEquipment record, @Param("example") TEquipmentExample example);

    int updateByExample(@Param("record") TEquipment record, @Param("example") TEquipmentExample example);

    //修改设备信息
    int updateByPrimaryKeySelective(TEquipment record);

    int updateByPrimaryKey(TEquipment record);

//    查询所有设备信息
    List<TEquipment> selectAllEquipment();

//    根据id查找设备信息
    TEquipment selectById(String id);

//  删除设备信息
    int deleteById(String id);

    TEquipment selectEquipmentNO(String equipmentNo);
}