package teenhealth.mybatis.po;

import java.util.Date;

public class TCardiopulmonary {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cardiopulmonary.id
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cardiopulmonary.student_id
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    private String studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cardiopulmonary.equipment_id
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    private String equipmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cardiopulmonary.first_speed
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    private Integer firstSpeed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cardiopulmonary.first_hr
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    private Integer firstHr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cardiopulmonary.first_power
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    private Integer firstPower;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cardiopulmonary.second_speed
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    private Integer secondSpeed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cardiopulmonary.second_hr
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    private Integer secondHr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cardiopulmonary.second_power
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    private Integer secondPower;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cardiopulmonary.max_power
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    private Integer maxPower;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cardiopulmonary.score
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    private Integer score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cardiopulmonary.heart_rate
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    private Integer heartRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cardiopulmonary.oxygen_uptake
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    private Double oxygenUptake;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cardiopulmonary.int_hr_k
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    private Double intHrK;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cardiopulmonary.int_hr_b
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    private Double intHrB;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cardiopulmonary.create_time
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cardiopulmonary.upload_time
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    private Date uploadTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cardiopulmonary.fc
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    private Double fc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cardiopulmonary.suggestion
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    private String suggestion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cardiopulmonary.id
     *
     * @return the value of t_cardiopulmonary.id
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cardiopulmonary.id
     *
     * @param id the value for t_cardiopulmonary.id
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cardiopulmonary.student_id
     *
     * @return the value of t_cardiopulmonary.student_id
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public String getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cardiopulmonary.student_id
     *
     * @param studentId the value for t_cardiopulmonary.student_id
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public void setStudentId(String studentId) {
        this.studentId = studentId == null ? null : studentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cardiopulmonary.equipment_id
     *
     * @return the value of t_cardiopulmonary.equipment_id
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public String getEquipmentId() {
        return equipmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cardiopulmonary.equipment_id
     *
     * @param equipmentId the value for t_cardiopulmonary.equipment_id
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public void setEquipmentId(String equipmentId) {
        this.equipmentId = equipmentId == null ? null : equipmentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cardiopulmonary.first_speed
     *
     * @return the value of t_cardiopulmonary.first_speed
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public Integer getFirstSpeed() {
        return firstSpeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cardiopulmonary.first_speed
     *
     * @param firstSpeed the value for t_cardiopulmonary.first_speed
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public void setFirstSpeed(Integer firstSpeed) {
        this.firstSpeed = firstSpeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cardiopulmonary.first_hr
     *
     * @return the value of t_cardiopulmonary.first_hr
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public Integer getFirstHr() {
        return firstHr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cardiopulmonary.first_hr
     *
     * @param firstHr the value for t_cardiopulmonary.first_hr
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public void setFirstHr(Integer firstHr) {
        this.firstHr = firstHr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cardiopulmonary.first_power
     *
     * @return the value of t_cardiopulmonary.first_power
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public Integer getFirstPower() {
        return firstPower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cardiopulmonary.first_power
     *
     * @param firstPower the value for t_cardiopulmonary.first_power
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public void setFirstPower(Integer firstPower) {
        this.firstPower = firstPower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cardiopulmonary.second_speed
     *
     * @return the value of t_cardiopulmonary.second_speed
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public Integer getSecondSpeed() {
        return secondSpeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cardiopulmonary.second_speed
     *
     * @param secondSpeed the value for t_cardiopulmonary.second_speed
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public void setSecondSpeed(Integer secondSpeed) {
        this.secondSpeed = secondSpeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cardiopulmonary.second_hr
     *
     * @return the value of t_cardiopulmonary.second_hr
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public Integer getSecondHr() {
        return secondHr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cardiopulmonary.second_hr
     *
     * @param secondHr the value for t_cardiopulmonary.second_hr
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public void setSecondHr(Integer secondHr) {
        this.secondHr = secondHr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cardiopulmonary.second_power
     *
     * @return the value of t_cardiopulmonary.second_power
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public Integer getSecondPower() {
        return secondPower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cardiopulmonary.second_power
     *
     * @param secondPower the value for t_cardiopulmonary.second_power
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public void setSecondPower(Integer secondPower) {
        this.secondPower = secondPower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cardiopulmonary.max_power
     *
     * @return the value of t_cardiopulmonary.max_power
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public Integer getMaxPower() {
        return maxPower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cardiopulmonary.max_power
     *
     * @param maxPower the value for t_cardiopulmonary.max_power
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public void setMaxPower(Integer maxPower) {
        this.maxPower = maxPower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cardiopulmonary.score
     *
     * @return the value of t_cardiopulmonary.score
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cardiopulmonary.score
     *
     * @param score the value for t_cardiopulmonary.score
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cardiopulmonary.heart_rate
     *
     * @return the value of t_cardiopulmonary.heart_rate
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public Integer getHeartRate() {
        return heartRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cardiopulmonary.heart_rate
     *
     * @param heartRate the value for t_cardiopulmonary.heart_rate
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public void setHeartRate(Integer heartRate) {
        this.heartRate = heartRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cardiopulmonary.oxygen_uptake
     *
     * @return the value of t_cardiopulmonary.oxygen_uptake
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public Double getOxygenUptake() {
        return oxygenUptake;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cardiopulmonary.oxygen_uptake
     *
     * @param oxygenUptake the value for t_cardiopulmonary.oxygen_uptake
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public void setOxygenUptake(Double oxygenUptake) {
        this.oxygenUptake = oxygenUptake;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cardiopulmonary.int_hr_k
     *
     * @return the value of t_cardiopulmonary.int_hr_k
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public Double getIntHrK() {
        return intHrK;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cardiopulmonary.int_hr_k
     *
     * @param intHrK the value for t_cardiopulmonary.int_hr_k
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public void setIntHrK(Double intHrK) {
        this.intHrK = intHrK;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cardiopulmonary.int_hr_b
     *
     * @return the value of t_cardiopulmonary.int_hr_b
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public Double getIntHrB() {
        return intHrB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cardiopulmonary.int_hr_b
     *
     * @param intHrB the value for t_cardiopulmonary.int_hr_b
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public void setIntHrB(Double intHrB) {
        this.intHrB = intHrB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cardiopulmonary.create_time
     *
     * @return the value of t_cardiopulmonary.create_time
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cardiopulmonary.create_time
     *
     * @param createTime the value for t_cardiopulmonary.create_time
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cardiopulmonary.upload_time
     *
     * @return the value of t_cardiopulmonary.upload_time
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public Date getUploadTime() {
        return uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cardiopulmonary.upload_time
     *
     * @param uploadTime the value for t_cardiopulmonary.upload_time
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public void setUploadTime(Date uploadTime) {
        this.uploadTime = uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cardiopulmonary.fc
     *
     * @return the value of t_cardiopulmonary.fc
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public Double getFc() {
        return fc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cardiopulmonary.fc
     *
     * @param fc the value for t_cardiopulmonary.fc
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public void setFc(Double fc) {
        this.fc = fc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cardiopulmonary.suggestion
     *
     * @return the value of t_cardiopulmonary.suggestion
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public String getSuggestion() {
        return suggestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cardiopulmonary.suggestion
     *
     * @param suggestion the value for t_cardiopulmonary.suggestion
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public void setSuggestion(String suggestion) {
        this.suggestion = suggestion == null ? null : suggestion.trim();
    }
}