package teenhealth.mybatis.po;

public class TClass {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class.id
     *
     * @mbggenerated Wed Apr 15 10:44:36 CST 2020
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class.class_name
     *
     * @mbggenerated Wed Apr 15 10:44:36 CST 2020
     */
    private String className;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class.teacher_id
     *
     * @mbggenerated Wed Apr 15 10:44:36 CST 2020
     */
    private String teacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class.grade_id
     *
     * @mbggenerated Wed Apr 15 10:44:36 CST 2020
     */
    private String gradeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class.class_code_id
     *
     * @mbggenerated Wed Apr 15 10:44:36 CST 2020
     */
    private String classCodeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class.school_id
     *
     * @mbggenerated Wed Apr 15 10:44:36 CST 2020
     */
    private String schoolId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class.remarke
     *
     * @mbggenerated Wed Apr 15 10:44:36 CST 2020
     */
    private String remarke;

     private Integer studentsNumber;

    private Integer isend;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class.id
     *
     * @return the value of t_class.id
     *
     * @mbggenerated Wed Apr 15 10:44:36 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class.id
     *
     * @param id the value for t_class.id
     *
     * @mbggenerated Wed Apr 15 10:44:36 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class.class_name
     *
     * @return the value of t_class.class_name
     *
     * @mbggenerated Wed Apr 15 10:44:36 CST 2020
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class.class_name
     *
     * @param className the value for t_class.class_name
     *
     * @mbggenerated Wed Apr 15 10:44:36 CST 2020
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class.teacher_id
     *
     * @return the value of t_class.teacher_id
     *
     * @mbggenerated Wed Apr 15 10:44:36 CST 2020
     */
    public String getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class.teacher_id
     *
     * @param teacherId the value for t_class.teacher_id
     *
     * @mbggenerated Wed Apr 15 10:44:36 CST 2020
     */
    public void setTeacherId(String teacherId) {
        this.teacherId = teacherId == null ? null : teacherId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class.grade_id
     *
     * @return the value of t_class.grade_id
     *
     * @mbggenerated Wed Apr 15 10:44:36 CST 2020
     */
    public String getGradeId() {
        return gradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class.grade_id
     *
     * @param gradeId the value for t_class.grade_id
     *
     * @mbggenerated Wed Apr 15 10:44:36 CST 2020
     */
    public void setGradeId(String gradeId) {
        this.gradeId = gradeId == null ? null : gradeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class.class_code_id
     *
     * @return the value of t_class.class_code_id
     *
     * @mbggenerated Wed Apr 15 10:44:36 CST 2020
     */
    public String getClassCodeId() {
        return classCodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class.class_code_id
     *
     * @param classCodeId the value for t_class.class_code_id
     *
     * @mbggenerated Wed Apr 15 10:44:36 CST 2020
     */
    public void setClassCodeId(String classCodeId) {
        this.classCodeId = classCodeId == null ? null : classCodeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class.school_id
     *
     * @return the value of t_class.school_id
     *
     * @mbggenerated Wed Apr 15 10:44:36 CST 2020
     */
    public String getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class.school_id
     *
     * @param schoolId the value for t_class.school_id
     *
     * @mbggenerated Wed Apr 15 10:44:36 CST 2020
     */
    public void setSchoolId(String schoolId) {
        this.schoolId = schoolId == null ? null : schoolId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class.remarke
     *
     * @return the value of t_class.remarke
     *
     * @mbggenerated Wed Apr 15 10:44:36 CST 2020
     */
    public String getRemarke() {
        return remarke;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class.remarke
     *
     * @param remarke the value for t_class.remarke
     *
     * @mbggenerated Wed Apr 15 10:44:36 CST 2020
     */
    public void setRemarke(String remarke) {
        this.remarke = remarke == null ? null : remarke.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class.isEnd
     *
     * @return the value of t_class.isEnd
     *
     * @mbggenerated Wed Apr 15 10:44:36 CST 2020
     */
    public Integer getIsend() {
        return isend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class.isEnd
     *
     * @param isend the value for t_class.isEnd
     *
     * @mbggenerated Wed Apr 15 10:44:36 CST 2020
     */
    public void setIsend(Integer isend) {
        this.isend = isend;
    }

    public Integer getStudentsNumber() {
        return studentsNumber;
    }

    public void setStudentsNumber(Integer studentsNumber) {
        this.studentsNumber = studentsNumber;
    }
}