package teenhealth.mybatis.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TEyesightExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_eyesight
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_eyesight
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_eyesight
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_eyesight
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public TEyesightExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_eyesight
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_eyesight
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_eyesight
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_eyesight
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_eyesight
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_eyesight
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_eyesight
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_eyesight
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_eyesight
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_eyesight
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_eyesight
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andStudentIdIsNull() {
            addCriterion("student_id is null");
            return (Criteria) this;
        }

        public Criteria andStudentIdIsNotNull() {
            addCriterion("student_id is not null");
            return (Criteria) this;
        }

        public Criteria andStudentIdEqualTo(String value) {
            addCriterion("student_id =", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotEqualTo(String value) {
            addCriterion("student_id <>", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdGreaterThan(String value) {
            addCriterion("student_id >", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdGreaterThanOrEqualTo(String value) {
            addCriterion("student_id >=", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdLessThan(String value) {
            addCriterion("student_id <", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdLessThanOrEqualTo(String value) {
            addCriterion("student_id <=", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdLike(String value) {
            addCriterion("student_id like", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotLike(String value) {
            addCriterion("student_id not like", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdIn(List<String> values) {
            addCriterion("student_id in", values, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotIn(List<String> values) {
            addCriterion("student_id not in", values, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdBetween(String value1, String value2) {
            addCriterion("student_id between", value1, value2, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotBetween(String value1, String value2) {
            addCriterion("student_id not between", value1, value2, "studentId");
            return (Criteria) this;
        }

        public Criteria andLeftNwzIsNull() {
            addCriterion("left_nwz is null");
            return (Criteria) this;
        }

        public Criteria andLeftNwzIsNotNull() {
            addCriterion("left_nwz is not null");
            return (Criteria) this;
        }

        public Criteria andLeftNwzEqualTo(String value) {
            addCriterion("left_nwz =", value, "leftNwz");
            return (Criteria) this;
        }

        public Criteria andLeftNwzNotEqualTo(String value) {
            addCriterion("left_nwz <>", value, "leftNwz");
            return (Criteria) this;
        }

        public Criteria andLeftNwzGreaterThan(String value) {
            addCriterion("left_nwz >", value, "leftNwz");
            return (Criteria) this;
        }

        public Criteria andLeftNwzGreaterThanOrEqualTo(String value) {
            addCriterion("left_nwz >=", value, "leftNwz");
            return (Criteria) this;
        }

        public Criteria andLeftNwzLessThan(String value) {
            addCriterion("left_nwz <", value, "leftNwz");
            return (Criteria) this;
        }

        public Criteria andLeftNwzLessThanOrEqualTo(String value) {
            addCriterion("left_nwz <=", value, "leftNwz");
            return (Criteria) this;
        }

        public Criteria andLeftNwzLike(String value) {
            addCriterion("left_nwz like", value, "leftNwz");
            return (Criteria) this;
        }

        public Criteria andLeftNwzNotLike(String value) {
            addCriterion("left_nwz not like", value, "leftNwz");
            return (Criteria) this;
        }

        public Criteria andLeftNwzIn(List<String> values) {
            addCriterion("left_nwz in", values, "leftNwz");
            return (Criteria) this;
        }

        public Criteria andLeftNwzNotIn(List<String> values) {
            addCriterion("left_nwz not in", values, "leftNwz");
            return (Criteria) this;
        }

        public Criteria andLeftNwzBetween(String value1, String value2) {
            addCriterion("left_nwz between", value1, value2, "leftNwz");
            return (Criteria) this;
        }

        public Criteria andLeftNwzNotBetween(String value1, String value2) {
            addCriterion("left_nwz not between", value1, value2, "leftNwz");
            return (Criteria) this;
        }

        public Criteria andRightNwzIsNull() {
            addCriterion("right_nwz is null");
            return (Criteria) this;
        }

        public Criteria andRightNwzIsNotNull() {
            addCriterion("right_nwz is not null");
            return (Criteria) this;
        }

        public Criteria andRightNwzEqualTo(String value) {
            addCriterion("right_nwz =", value, "rightNwz");
            return (Criteria) this;
        }

        public Criteria andRightNwzNotEqualTo(String value) {
            addCriterion("right_nwz <>", value, "rightNwz");
            return (Criteria) this;
        }

        public Criteria andRightNwzGreaterThan(String value) {
            addCriterion("right_nwz >", value, "rightNwz");
            return (Criteria) this;
        }

        public Criteria andRightNwzGreaterThanOrEqualTo(String value) {
            addCriterion("right_nwz >=", value, "rightNwz");
            return (Criteria) this;
        }

        public Criteria andRightNwzLessThan(String value) {
            addCriterion("right_nwz <", value, "rightNwz");
            return (Criteria) this;
        }

        public Criteria andRightNwzLessThanOrEqualTo(String value) {
            addCriterion("right_nwz <=", value, "rightNwz");
            return (Criteria) this;
        }

        public Criteria andRightNwzLike(String value) {
            addCriterion("right_nwz like", value, "rightNwz");
            return (Criteria) this;
        }

        public Criteria andRightNwzNotLike(String value) {
            addCriterion("right_nwz not like", value, "rightNwz");
            return (Criteria) this;
        }

        public Criteria andRightNwzIn(List<String> values) {
            addCriterion("right_nwz in", values, "rightNwz");
            return (Criteria) this;
        }

        public Criteria andRightNwzNotIn(List<String> values) {
            addCriterion("right_nwz not in", values, "rightNwz");
            return (Criteria) this;
        }

        public Criteria andRightNwzBetween(String value1, String value2) {
            addCriterion("right_nwz between", value1, value2, "rightNwz");
            return (Criteria) this;
        }

        public Criteria andRightNwzNotBetween(String value1, String value2) {
            addCriterion("right_nwz not between", value1, value2, "rightNwz");
            return (Criteria) this;
        }

        public Criteria andLeftSxzIsNull() {
            addCriterion("left_sxz is null");
            return (Criteria) this;
        }

        public Criteria andLeftSxzIsNotNull() {
            addCriterion("left_sxz is not null");
            return (Criteria) this;
        }

        public Criteria andLeftSxzEqualTo(String value) {
            addCriterion("left_sxz =", value, "leftSxz");
            return (Criteria) this;
        }

        public Criteria andLeftSxzNotEqualTo(String value) {
            addCriterion("left_sxz <>", value, "leftSxz");
            return (Criteria) this;
        }

        public Criteria andLeftSxzGreaterThan(String value) {
            addCriterion("left_sxz >", value, "leftSxz");
            return (Criteria) this;
        }

        public Criteria andLeftSxzGreaterThanOrEqualTo(String value) {
            addCriterion("left_sxz >=", value, "leftSxz");
            return (Criteria) this;
        }

        public Criteria andLeftSxzLessThan(String value) {
            addCriterion("left_sxz <", value, "leftSxz");
            return (Criteria) this;
        }

        public Criteria andLeftSxzLessThanOrEqualTo(String value) {
            addCriterion("left_sxz <=", value, "leftSxz");
            return (Criteria) this;
        }

        public Criteria andLeftSxzLike(String value) {
            addCriterion("left_sxz like", value, "leftSxz");
            return (Criteria) this;
        }

        public Criteria andLeftSxzNotLike(String value) {
            addCriterion("left_sxz not like", value, "leftSxz");
            return (Criteria) this;
        }

        public Criteria andLeftSxzIn(List<String> values) {
            addCriterion("left_sxz in", values, "leftSxz");
            return (Criteria) this;
        }

        public Criteria andLeftSxzNotIn(List<String> values) {
            addCriterion("left_sxz not in", values, "leftSxz");
            return (Criteria) this;
        }

        public Criteria andLeftSxzBetween(String value1, String value2) {
            addCriterion("left_sxz between", value1, value2, "leftSxz");
            return (Criteria) this;
        }

        public Criteria andLeftSxzNotBetween(String value1, String value2) {
            addCriterion("left_sxz not between", value1, value2, "leftSxz");
            return (Criteria) this;
        }

        public Criteria andRightSxzIsNull() {
            addCriterion("right_sxz is null");
            return (Criteria) this;
        }

        public Criteria andRightSxzIsNotNull() {
            addCriterion("right_sxz is not null");
            return (Criteria) this;
        }

        public Criteria andRightSxzEqualTo(String value) {
            addCriterion("right_sxz =", value, "rightSxz");
            return (Criteria) this;
        }

        public Criteria andRightSxzNotEqualTo(String value) {
            addCriterion("right_sxz <>", value, "rightSxz");
            return (Criteria) this;
        }

        public Criteria andRightSxzGreaterThan(String value) {
            addCriterion("right_sxz >", value, "rightSxz");
            return (Criteria) this;
        }

        public Criteria andRightSxzGreaterThanOrEqualTo(String value) {
            addCriterion("right_sxz >=", value, "rightSxz");
            return (Criteria) this;
        }

        public Criteria andRightSxzLessThan(String value) {
            addCriterion("right_sxz <", value, "rightSxz");
            return (Criteria) this;
        }

        public Criteria andRightSxzLessThanOrEqualTo(String value) {
            addCriterion("right_sxz <=", value, "rightSxz");
            return (Criteria) this;
        }

        public Criteria andRightSxzLike(String value) {
            addCriterion("right_sxz like", value, "rightSxz");
            return (Criteria) this;
        }

        public Criteria andRightSxzNotLike(String value) {
            addCriterion("right_sxz not like", value, "rightSxz");
            return (Criteria) this;
        }

        public Criteria andRightSxzIn(List<String> values) {
            addCriterion("right_sxz in", values, "rightSxz");
            return (Criteria) this;
        }

        public Criteria andRightSxzNotIn(List<String> values) {
            addCriterion("right_sxz not in", values, "rightSxz");
            return (Criteria) this;
        }

        public Criteria andRightSxzBetween(String value1, String value2) {
            addCriterion("right_sxz between", value1, value2, "rightSxz");
            return (Criteria) this;
        }

        public Criteria andRightSxzNotBetween(String value1, String value2) {
            addCriterion("right_sxz not between", value1, value2, "rightSxz");
            return (Criteria) this;
        }

        public Criteria andLeftSxxIsNull() {
            addCriterion("left_sxx is null");
            return (Criteria) this;
        }

        public Criteria andLeftSxxIsNotNull() {
            addCriterion("left_sxx is not null");
            return (Criteria) this;
        }

        public Criteria andLeftSxxEqualTo(String value) {
            addCriterion("left_sxx =", value, "leftSxx");
            return (Criteria) this;
        }

        public Criteria andLeftSxxNotEqualTo(String value) {
            addCriterion("left_sxx <>", value, "leftSxx");
            return (Criteria) this;
        }

        public Criteria andLeftSxxGreaterThan(String value) {
            addCriterion("left_sxx >", value, "leftSxx");
            return (Criteria) this;
        }

        public Criteria andLeftSxxGreaterThanOrEqualTo(String value) {
            addCriterion("left_sxx >=", value, "leftSxx");
            return (Criteria) this;
        }

        public Criteria andLeftSxxLessThan(String value) {
            addCriterion("left_sxx <", value, "leftSxx");
            return (Criteria) this;
        }

        public Criteria andLeftSxxLessThanOrEqualTo(String value) {
            addCriterion("left_sxx <=", value, "leftSxx");
            return (Criteria) this;
        }

        public Criteria andLeftSxxLike(String value) {
            addCriterion("left_sxx like", value, "leftSxx");
            return (Criteria) this;
        }

        public Criteria andLeftSxxNotLike(String value) {
            addCriterion("left_sxx not like", value, "leftSxx");
            return (Criteria) this;
        }

        public Criteria andLeftSxxIn(List<String> values) {
            addCriterion("left_sxx in", values, "leftSxx");
            return (Criteria) this;
        }

        public Criteria andLeftSxxNotIn(List<String> values) {
            addCriterion("left_sxx not in", values, "leftSxx");
            return (Criteria) this;
        }

        public Criteria andLeftSxxBetween(String value1, String value2) {
            addCriterion("left_sxx between", value1, value2, "leftSxx");
            return (Criteria) this;
        }

        public Criteria andLeftSxxNotBetween(String value1, String value2) {
            addCriterion("left_sxx not between", value1, value2, "leftSxx");
            return (Criteria) this;
        }

        public Criteria andRightSxxIsNull() {
            addCriterion("right_sxx is null");
            return (Criteria) this;
        }

        public Criteria andRightSxxIsNotNull() {
            addCriterion("right_sxx is not null");
            return (Criteria) this;
        }

        public Criteria andRightSxxEqualTo(String value) {
            addCriterion("right_sxx =", value, "rightSxx");
            return (Criteria) this;
        }

        public Criteria andRightSxxNotEqualTo(String value) {
            addCriterion("right_sxx <>", value, "rightSxx");
            return (Criteria) this;
        }

        public Criteria andRightSxxGreaterThan(String value) {
            addCriterion("right_sxx >", value, "rightSxx");
            return (Criteria) this;
        }

        public Criteria andRightSxxGreaterThanOrEqualTo(String value) {
            addCriterion("right_sxx >=", value, "rightSxx");
            return (Criteria) this;
        }

        public Criteria andRightSxxLessThan(String value) {
            addCriterion("right_sxx <", value, "rightSxx");
            return (Criteria) this;
        }

        public Criteria andRightSxxLessThanOrEqualTo(String value) {
            addCriterion("right_sxx <=", value, "rightSxx");
            return (Criteria) this;
        }

        public Criteria andRightSxxLike(String value) {
            addCriterion("right_sxx like", value, "rightSxx");
            return (Criteria) this;
        }

        public Criteria andRightSxxNotLike(String value) {
            addCriterion("right_sxx not like", value, "rightSxx");
            return (Criteria) this;
        }

        public Criteria andRightSxxIn(List<String> values) {
            addCriterion("right_sxx in", values, "rightSxx");
            return (Criteria) this;
        }

        public Criteria andRightSxxNotIn(List<String> values) {
            addCriterion("right_sxx not in", values, "rightSxx");
            return (Criteria) this;
        }

        public Criteria andRightSxxBetween(String value1, String value2) {
            addCriterion("right_sxx between", value1, value2, "rightSxx");
            return (Criteria) this;
        }

        public Criteria andRightSxxNotBetween(String value1, String value2) {
            addCriterion("right_sxx not between", value1, value2, "rightSxx");
            return (Criteria) this;
        }

        public Criteria andTestadviceIsNull() {
            addCriterion("testAdvice is null");
            return (Criteria) this;
        }

        public Criteria andTestadviceIsNotNull() {
            addCriterion("testAdvice is not null");
            return (Criteria) this;
        }

        public Criteria andTestadviceEqualTo(String value) {
            addCriterion("testAdvice =", value, "testadvice");
            return (Criteria) this;
        }

        public Criteria andTestadviceNotEqualTo(String value) {
            addCriterion("testAdvice <>", value, "testadvice");
            return (Criteria) this;
        }

        public Criteria andTestadviceGreaterThan(String value) {
            addCriterion("testAdvice >", value, "testadvice");
            return (Criteria) this;
        }

        public Criteria andTestadviceGreaterThanOrEqualTo(String value) {
            addCriterion("testAdvice >=", value, "testadvice");
            return (Criteria) this;
        }

        public Criteria andTestadviceLessThan(String value) {
            addCriterion("testAdvice <", value, "testadvice");
            return (Criteria) this;
        }

        public Criteria andTestadviceLessThanOrEqualTo(String value) {
            addCriterion("testAdvice <=", value, "testadvice");
            return (Criteria) this;
        }

        public Criteria andTestadviceLike(String value) {
            addCriterion("testAdvice like", value, "testadvice");
            return (Criteria) this;
        }

        public Criteria andTestadviceNotLike(String value) {
            addCriterion("testAdvice not like", value, "testadvice");
            return (Criteria) this;
        }

        public Criteria andTestadviceIn(List<String> values) {
            addCriterion("testAdvice in", values, "testadvice");
            return (Criteria) this;
        }

        public Criteria andTestadviceNotIn(List<String> values) {
            addCriterion("testAdvice not in", values, "testadvice");
            return (Criteria) this;
        }

        public Criteria andTestadviceBetween(String value1, String value2) {
            addCriterion("testAdvice between", value1, value2, "testadvice");
            return (Criteria) this;
        }

        public Criteria andTestadviceNotBetween(String value1, String value2) {
            addCriterion("testAdvice not between", value1, value2, "testadvice");
            return (Criteria) this;
        }

        public Criteria andTrainplanIsNull() {
            addCriterion("trainPlan is null");
            return (Criteria) this;
        }

        public Criteria andTrainplanIsNotNull() {
            addCriterion("trainPlan is not null");
            return (Criteria) this;
        }

        public Criteria andTrainplanEqualTo(String value) {
            addCriterion("trainPlan =", value, "trainplan");
            return (Criteria) this;
        }

        public Criteria andTrainplanNotEqualTo(String value) {
            addCriterion("trainPlan <>", value, "trainplan");
            return (Criteria) this;
        }

        public Criteria andTrainplanGreaterThan(String value) {
            addCriterion("trainPlan >", value, "trainplan");
            return (Criteria) this;
        }

        public Criteria andTrainplanGreaterThanOrEqualTo(String value) {
            addCriterion("trainPlan >=", value, "trainplan");
            return (Criteria) this;
        }

        public Criteria andTrainplanLessThan(String value) {
            addCriterion("trainPlan <", value, "trainplan");
            return (Criteria) this;
        }

        public Criteria andTrainplanLessThanOrEqualTo(String value) {
            addCriterion("trainPlan <=", value, "trainplan");
            return (Criteria) this;
        }

        public Criteria andTrainplanLike(String value) {
            addCriterion("trainPlan like", value, "trainplan");
            return (Criteria) this;
        }

        public Criteria andTrainplanNotLike(String value) {
            addCriterion("trainPlan not like", value, "trainplan");
            return (Criteria) this;
        }

        public Criteria andTrainplanIn(List<String> values) {
            addCriterion("trainPlan in", values, "trainplan");
            return (Criteria) this;
        }

        public Criteria andTrainplanNotIn(List<String> values) {
            addCriterion("trainPlan not in", values, "trainplan");
            return (Criteria) this;
        }

        public Criteria andTrainplanBetween(String value1, String value2) {
            addCriterion("trainPlan between", value1, value2, "trainplan");
            return (Criteria) this;
        }

        public Criteria andTrainplanNotBetween(String value1, String value2) {
            addCriterion("trainPlan not between", value1, value2, "trainplan");
            return (Criteria) this;
        }

        public Criteria andEatingadviceIsNull() {
            addCriterion("eatingAdvice is null");
            return (Criteria) this;
        }

        public Criteria andEatingadviceIsNotNull() {
            addCriterion("eatingAdvice is not null");
            return (Criteria) this;
        }

        public Criteria andEatingadviceEqualTo(String value) {
            addCriterion("eatingAdvice =", value, "eatingadvice");
            return (Criteria) this;
        }

        public Criteria andEatingadviceNotEqualTo(String value) {
            addCriterion("eatingAdvice <>", value, "eatingadvice");
            return (Criteria) this;
        }

        public Criteria andEatingadviceGreaterThan(String value) {
            addCriterion("eatingAdvice >", value, "eatingadvice");
            return (Criteria) this;
        }

        public Criteria andEatingadviceGreaterThanOrEqualTo(String value) {
            addCriterion("eatingAdvice >=", value, "eatingadvice");
            return (Criteria) this;
        }

        public Criteria andEatingadviceLessThan(String value) {
            addCriterion("eatingAdvice <", value, "eatingadvice");
            return (Criteria) this;
        }

        public Criteria andEatingadviceLessThanOrEqualTo(String value) {
            addCriterion("eatingAdvice <=", value, "eatingadvice");
            return (Criteria) this;
        }

        public Criteria andEatingadviceLike(String value) {
            addCriterion("eatingAdvice like", value, "eatingadvice");
            return (Criteria) this;
        }

        public Criteria andEatingadviceNotLike(String value) {
            addCriterion("eatingAdvice not like", value, "eatingadvice");
            return (Criteria) this;
        }

        public Criteria andEatingadviceIn(List<String> values) {
            addCriterion("eatingAdvice in", values, "eatingadvice");
            return (Criteria) this;
        }

        public Criteria andEatingadviceNotIn(List<String> values) {
            addCriterion("eatingAdvice not in", values, "eatingadvice");
            return (Criteria) this;
        }

        public Criteria andEatingadviceBetween(String value1, String value2) {
            addCriterion("eatingAdvice between", value1, value2, "eatingadvice");
            return (Criteria) this;
        }

        public Criteria andEatingadviceNotBetween(String value1, String value2) {
            addCriterion("eatingAdvice not between", value1, value2, "eatingadvice");
            return (Criteria) this;
        }

        public Criteria andExecisingadviceIsNull() {
            addCriterion("execisingAdvice is null");
            return (Criteria) this;
        }

        public Criteria andExecisingadviceIsNotNull() {
            addCriterion("execisingAdvice is not null");
            return (Criteria) this;
        }

        public Criteria andExecisingadviceEqualTo(String value) {
            addCriterion("execisingAdvice =", value, "execisingadvice");
            return (Criteria) this;
        }

        public Criteria andExecisingadviceNotEqualTo(String value) {
            addCriterion("execisingAdvice <>", value, "execisingadvice");
            return (Criteria) this;
        }

        public Criteria andExecisingadviceGreaterThan(String value) {
            addCriterion("execisingAdvice >", value, "execisingadvice");
            return (Criteria) this;
        }

        public Criteria andExecisingadviceGreaterThanOrEqualTo(String value) {
            addCriterion("execisingAdvice >=", value, "execisingadvice");
            return (Criteria) this;
        }

        public Criteria andExecisingadviceLessThan(String value) {
            addCriterion("execisingAdvice <", value, "execisingadvice");
            return (Criteria) this;
        }

        public Criteria andExecisingadviceLessThanOrEqualTo(String value) {
            addCriterion("execisingAdvice <=", value, "execisingadvice");
            return (Criteria) this;
        }

        public Criteria andExecisingadviceLike(String value) {
            addCriterion("execisingAdvice like", value, "execisingadvice");
            return (Criteria) this;
        }

        public Criteria andExecisingadviceNotLike(String value) {
            addCriterion("execisingAdvice not like", value, "execisingadvice");
            return (Criteria) this;
        }

        public Criteria andExecisingadviceIn(List<String> values) {
            addCriterion("execisingAdvice in", values, "execisingadvice");
            return (Criteria) this;
        }

        public Criteria andExecisingadviceNotIn(List<String> values) {
            addCriterion("execisingAdvice not in", values, "execisingadvice");
            return (Criteria) this;
        }

        public Criteria andExecisingadviceBetween(String value1, String value2) {
            addCriterion("execisingAdvice between", value1, value2, "execisingadvice");
            return (Criteria) this;
        }

        public Criteria andExecisingadviceNotBetween(String value1, String value2) {
            addCriterion("execisingAdvice not between", value1, value2, "execisingadvice");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUploadtimeIsNull() {
            addCriterion("uploadTime is null");
            return (Criteria) this;
        }

        public Criteria andUploadtimeIsNotNull() {
            addCriterion("uploadTime is not null");
            return (Criteria) this;
        }

        public Criteria andUploadtimeEqualTo(Date value) {
            addCriterion("uploadTime =", value, "uploadtime");
            return (Criteria) this;
        }

        public Criteria andUploadtimeNotEqualTo(Date value) {
            addCriterion("uploadTime <>", value, "uploadtime");
            return (Criteria) this;
        }

        public Criteria andUploadtimeGreaterThan(Date value) {
            addCriterion("uploadTime >", value, "uploadtime");
            return (Criteria) this;
        }

        public Criteria andUploadtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("uploadTime >=", value, "uploadtime");
            return (Criteria) this;
        }

        public Criteria andUploadtimeLessThan(Date value) {
            addCriterion("uploadTime <", value, "uploadtime");
            return (Criteria) this;
        }

        public Criteria andUploadtimeLessThanOrEqualTo(Date value) {
            addCriterion("uploadTime <=", value, "uploadtime");
            return (Criteria) this;
        }

        public Criteria andUploadtimeIn(List<Date> values) {
            addCriterion("uploadTime in", values, "uploadtime");
            return (Criteria) this;
        }

        public Criteria andUploadtimeNotIn(List<Date> values) {
            addCriterion("uploadTime not in", values, "uploadtime");
            return (Criteria) this;
        }

        public Criteria andUploadtimeBetween(Date value1, Date value2) {
            addCriterion("uploadTime between", value1, value2, "uploadtime");
            return (Criteria) this;
        }

        public Criteria andUploadtimeNotBetween(Date value1, Date value2) {
            addCriterion("uploadTime not between", value1, value2, "uploadtime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_eyesight
     *
     * @mbggenerated do_not_delete_during_merge Sat Mar 07 21:35:32 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_eyesight
     *
     * @mbggenerated Sat Mar 07 21:35:32 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}