package teenhealth.mybatis.po;

import java.util.Date;

public class TSomaticGameRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_somatic_game_record.id
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_somatic_game_record.student_id
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    private String studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_somatic_game_record.plan_id
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    private String planId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_somatic_game_record.train_mode
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    private Integer trainMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_somatic_game_record.mode_escape
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    private Integer modeEscape;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_somatic_game_record.escape_time
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    private Integer escapeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_somatic_game_record.level_escape_train
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    private Integer levelEscapeTrain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_somatic_game_record.num_eleg_up
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    private Integer numElegUp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_somatic_game_record.num_squat
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    private Integer numSquat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_somatic_game_record.num_jump
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    private Integer numJump;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_somatic_game_record.num_not_leg_lift
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    private Integer numNotLegLift;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_somatic_game_record.num_not_squat
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    private Integer numNotSquat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_somatic_game_record.num_not_jump
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    private Integer numNotJump;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_somatic_game_record.num_diamond
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    private Integer numDiamond;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_somatic_game_record.score_esecape
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    private Integer scoreEsecape;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_somatic_game_record.create_time
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_somatic_game_record.upload_time
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    private Date uploadTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_somatic_game_record.id
     *
     * @return the value of t_somatic_game_record.id
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_somatic_game_record.id
     *
     * @param id the value for t_somatic_game_record.id
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_somatic_game_record.student_id
     *
     * @return the value of t_somatic_game_record.student_id
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public String getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_somatic_game_record.student_id
     *
     * @param studentId the value for t_somatic_game_record.student_id
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public void setStudentId(String studentId) {
        this.studentId = studentId == null ? null : studentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_somatic_game_record.plan_id
     *
     * @return the value of t_somatic_game_record.plan_id
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public String getPlanId() {
        return planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_somatic_game_record.plan_id
     *
     * @param planId the value for t_somatic_game_record.plan_id
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public void setPlanId(String planId) {
        this.planId = planId == null ? null : planId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_somatic_game_record.train_mode
     *
     * @return the value of t_somatic_game_record.train_mode
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public Integer getTrainMode() {
        return trainMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_somatic_game_record.train_mode
     *
     * @param trainMode the value for t_somatic_game_record.train_mode
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public void setTrainMode(Integer trainMode) {
        this.trainMode = trainMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_somatic_game_record.mode_escape
     *
     * @return the value of t_somatic_game_record.mode_escape
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public Integer getModeEscape() {
        return modeEscape;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_somatic_game_record.mode_escape
     *
     * @param modeEscape the value for t_somatic_game_record.mode_escape
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public void setModeEscape(Integer modeEscape) {
        this.modeEscape = modeEscape;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_somatic_game_record.escape_time
     *
     * @return the value of t_somatic_game_record.escape_time
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public Integer getEscapeTime() {
        return escapeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_somatic_game_record.escape_time
     *
     * @param escapeTime the value for t_somatic_game_record.escape_time
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public void setEscapeTime(Integer escapeTime) {
        this.escapeTime = escapeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_somatic_game_record.level_escape_train
     *
     * @return the value of t_somatic_game_record.level_escape_train
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public Integer getLevelEscapeTrain() {
        return levelEscapeTrain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_somatic_game_record.level_escape_train
     *
     * @param levelEscapeTrain the value for t_somatic_game_record.level_escape_train
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public void setLevelEscapeTrain(Integer levelEscapeTrain) {
        this.levelEscapeTrain = levelEscapeTrain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_somatic_game_record.num_eleg_up
     *
     * @return the value of t_somatic_game_record.num_eleg_up
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public Integer getNumElegUp() {
        return numElegUp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_somatic_game_record.num_eleg_up
     *
     * @param numElegUp the value for t_somatic_game_record.num_eleg_up
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public void setNumElegUp(Integer numElegUp) {
        this.numElegUp = numElegUp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_somatic_game_record.num_squat
     *
     * @return the value of t_somatic_game_record.num_squat
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public Integer getNumSquat() {
        return numSquat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_somatic_game_record.num_squat
     *
     * @param numSquat the value for t_somatic_game_record.num_squat
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public void setNumSquat(Integer numSquat) {
        this.numSquat = numSquat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_somatic_game_record.num_jump
     *
     * @return the value of t_somatic_game_record.num_jump
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public Integer getNumJump() {
        return numJump;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_somatic_game_record.num_jump
     *
     * @param numJump the value for t_somatic_game_record.num_jump
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public void setNumJump(Integer numJump) {
        this.numJump = numJump;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_somatic_game_record.num_not_leg_lift
     *
     * @return the value of t_somatic_game_record.num_not_leg_lift
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public Integer getNumNotLegLift() {
        return numNotLegLift;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_somatic_game_record.num_not_leg_lift
     *
     * @param numNotLegLift the value for t_somatic_game_record.num_not_leg_lift
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public void setNumNotLegLift(Integer numNotLegLift) {
        this.numNotLegLift = numNotLegLift;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_somatic_game_record.num_not_squat
     *
     * @return the value of t_somatic_game_record.num_not_squat
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public Integer getNumNotSquat() {
        return numNotSquat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_somatic_game_record.num_not_squat
     *
     * @param numNotSquat the value for t_somatic_game_record.num_not_squat
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public void setNumNotSquat(Integer numNotSquat) {
        this.numNotSquat = numNotSquat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_somatic_game_record.num_not_jump
     *
     * @return the value of t_somatic_game_record.num_not_jump
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public Integer getNumNotJump() {
        return numNotJump;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_somatic_game_record.num_not_jump
     *
     * @param numNotJump the value for t_somatic_game_record.num_not_jump
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public void setNumNotJump(Integer numNotJump) {
        this.numNotJump = numNotJump;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_somatic_game_record.num_diamond
     *
     * @return the value of t_somatic_game_record.num_diamond
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public Integer getNumDiamond() {
        return numDiamond;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_somatic_game_record.num_diamond
     *
     * @param numDiamond the value for t_somatic_game_record.num_diamond
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public void setNumDiamond(Integer numDiamond) {
        this.numDiamond = numDiamond;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_somatic_game_record.score_esecape
     *
     * @return the value of t_somatic_game_record.score_esecape
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public Integer getScoreEsecape() {
        return scoreEsecape;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_somatic_game_record.score_esecape
     *
     * @param scoreEsecape the value for t_somatic_game_record.score_esecape
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public void setScoreEsecape(Integer scoreEsecape) {
        this.scoreEsecape = scoreEsecape;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_somatic_game_record.create_time
     *
     * @return the value of t_somatic_game_record.create_time
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_somatic_game_record.create_time
     *
     * @param createTime the value for t_somatic_game_record.create_time
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_somatic_game_record.upload_time
     *
     * @return the value of t_somatic_game_record.upload_time
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public Date getUploadTime() {
        return uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_somatic_game_record.upload_time
     *
     * @param uploadTime the value for t_somatic_game_record.upload_time
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public void setUploadTime(Date uploadTime) {
        this.uploadTime = uploadTime;
    }
}