package teenhealth.mybatis.po;

import java.util.Date;

public class TSomaticGamePlan {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_somatic_game_plan.id
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_somatic_game_plan.student_id
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    private String studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_somatic_game_plan.exemode
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    private Integer exemode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_somatic_game_plan.exedue
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    private Integer exedue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_somatic_game_plan.exediff
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    private Integer exediff;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_somatic_game_plan.exefreq
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    private Integer exefreq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_somatic_game_plan.execycle
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    private Integer execycle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_somatic_game_plan.is_enable
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    private Integer isEnable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_somatic_game_plan.create_time
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_somatic_game_plan.id
     *
     * @return the value of t_somatic_game_plan.id
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_somatic_game_plan.id
     *
     * @param id the value for t_somatic_game_plan.id
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_somatic_game_plan.student_id
     *
     * @return the value of t_somatic_game_plan.student_id
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public String getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_somatic_game_plan.student_id
     *
     * @param studentId the value for t_somatic_game_plan.student_id
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public void setStudentId(String studentId) {
        this.studentId = studentId == null ? null : studentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_somatic_game_plan.exemode
     *
     * @return the value of t_somatic_game_plan.exemode
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public Integer getExemode() {
        return exemode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_somatic_game_plan.exemode
     *
     * @param exemode the value for t_somatic_game_plan.exemode
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public void setExemode(Integer exemode) {
        this.exemode = exemode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_somatic_game_plan.exedue
     *
     * @return the value of t_somatic_game_plan.exedue
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public Integer getExedue() {
        return exedue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_somatic_game_plan.exedue
     *
     * @param exedue the value for t_somatic_game_plan.exedue
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public void setExedue(Integer exedue) {
        this.exedue = exedue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_somatic_game_plan.exediff
     *
     * @return the value of t_somatic_game_plan.exediff
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public Integer getExediff() {
        return exediff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_somatic_game_plan.exediff
     *
     * @param exediff the value for t_somatic_game_plan.exediff
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public void setExediff(Integer exediff) {
        this.exediff = exediff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_somatic_game_plan.exefreq
     *
     * @return the value of t_somatic_game_plan.exefreq
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public Integer getExefreq() {
        return exefreq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_somatic_game_plan.exefreq
     *
     * @param exefreq the value for t_somatic_game_plan.exefreq
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public void setExefreq(Integer exefreq) {
        this.exefreq = exefreq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_somatic_game_plan.execycle
     *
     * @return the value of t_somatic_game_plan.execycle
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public Integer getExecycle() {
        return execycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_somatic_game_plan.execycle
     *
     * @param execycle the value for t_somatic_game_plan.execycle
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public void setExecycle(Integer execycle) {
        this.execycle = execycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_somatic_game_plan.is_enable
     *
     * @return the value of t_somatic_game_plan.is_enable
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public Integer getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_somatic_game_plan.is_enable
     *
     * @param isEnable the value for t_somatic_game_plan.is_enable
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public void setIsEnable(Integer isEnable) {
        this.isEnable = isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_somatic_game_plan.create_time
     *
     * @return the value of t_somatic_game_plan.create_time
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_somatic_game_plan.create_time
     *
     * @param createTime the value for t_somatic_game_plan.create_time
     *
     * @mbggenerated Mon Mar 23 10:53:04 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}